### ISSUE TITLE
[asking]

### ISSUE THREAD

**Issue by ifoverload** [DottieDot/GtaPoolExtender#1]
what is this for? does it relate to something like spawning?
is there a post/thread that i can read about this?
i see those 'adjustment' wrappers, but i dont know what i need to fill. can u post an example?
*thanks, sorry for english

**Comment by DottieDot** [comment]
Hey, this mod allows you to extend the game pools without modifying gameconfig.xml. It's still a work in progress and I'm planning on adding the ability to modify other config entries too. The end goal is to prevent the need for a modified gameconfig.xml that has to be modified every update.

If you'd like to try it out you'll have to create a "PoolAdjustments" folder in your game directory. Inside of that folder, you can place json files to extend certain pools. The format is as follows: 
```json
{
  "Object": "+100"
} 
```
This would increase the `Object` pool by 100. Alternatively, you can use `>` instead of `+`, doing this will set the pool size to the given amount, or more, depending on the other adjustments. 

Eventually, this format will change when other config items can be modified too. I'll make a proper readme after doing this.

**Comment by ifoverload** [comment]
hey thanks for explaining & the project
however i nearly understand that detour just overriding the original return size right?
but i'd like to know what that 'pools size' inside the gameconfig.xml effect/do to the game?
is there something i can test?
seems interesting to me 💯

**Comment by DottieDot** [comment]
> However I nearly understand that detour just overriding the original return size right?

![Detour hook](https://nagareshwar.securityxploded.com/wp-content/uploads/2014/03/detour.png)

> But I'd like to know what that 'pools size' inside the gameconfig.xml effect/do to the game?

A pool simply stores the data for a given item. Extending them means you can have more of those items. Setting the "Vehicles" pool to 200 means you'll be able to have 200 vehicles in the world, instead of the default 148.

> Is there something I can test?

If you have a need for it you can use it 🤷‍♂️. No specific testing has to be done at this moment.

**Comment by ifoverload** [comment]
that's really clear now i understand, and yes i absolutely needed it!
i just noticed if the game are getting size of some pools exactly once when the game started
and i giving a try to increasing this "Peds" pools to 300 (default 256)
running spawnped, the game crash when reaching around 244-256 pools value, but its fine when im not increasing it.
do you know by any chance why? i basically wanted to increasing spawn limit

**Comment by DottieDot** [comment]
Please make a separate issue for that.
